# Generated by Django 5.1.5 on 2025-01-24 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="sender",
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(default="CREDITO", max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
